baseURL = 'https://music.oxyde.fun/'
languageCode = 'en-us'
title = 'FÃªte de la musique'
theme = 'PaperMod'
sectionPagesMenu = 'main'
enableEmoji = 'true'
[menus]
  [[menus.main]]
    name = 'Archives'
    pageRef = '/archives/'
    weight = 10
[params]
    defaultTheme = 'dark'
    ShowAllPagesInArchive = 'true'
    ShowToc = 'true'
    ShowRssButtonInSectionTermList = 'true'
   